import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { LeftSidebar } from "./_components/left-sidebar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "CS Engineering Test Project",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <div className="flex h-[100vh] items-start">
            <LeftSidebar />
            <div className="pl-[143px] pt-10">
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </div>
            <Toaster />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
